### ISSUE TITLE
update to ASP.NET Core 2.0

### ISSUE THREAD

**Issue by damienbod** [damienbod/AngularWebpackVisualStudio#108]

**Comment by damienbod** [comment]
Updated
https://github.com/damienbod/AngularWebpackVisualStudio/tree/aspnetcore_2_0_0

We have to wait until the CI updates to 2.0

**Comment by damienbod** [comment]
@robisim74 @FabianGosebrink ASP.NET Core 2.0 is ready.

Switch now?

Greetings Damien

**Comment by FabianGosebrink** [comment]
IMHO : Yes. 
Sent from NineFrom: damienbod <notifications@github.com>Sent: Aug 18, 2017 15:33To: damienbod/AngularWebpackVisualStudioCc: Fabian Gosebrink; MentionSubject: Re: [damienbod/AngularWebpackVisualStudio] update to ASP.NET Core 2.0 (#108)@robisim74 @FabianGosebrink ASP.NET Core 2.0 is ready.
Switch now?
Greetings Damien

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/damienbod/AngularWebpackVisualStudio","title":"damienbod/AngularWebpackVisualStudio","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/damienbod/AngularWebpackVisualStudio"}},"updates":{"snippets":[{"icon":"PERSON","message":"@damienbod in #108: @robisim74 @FabianGosebrink ASP.NET Core 2.0 is ready.\r\n\r\nSwitch now?\r\n\r\nGreetings Damien"}],"action":{"name":"View Issue","url":"https://github.com/damienbod/AngularWebpackVisualStudio/issues/108#issuecomment-323354630"}}}

**Comment by FabianGosebrink** [comment]
IMHO: Yes.

**Comment by robisim74** [comment]
Great!

**Comment by FabianGosebrink** [comment]
@damienbod will you do? Can back you up on the weekend, tomorrow the earliest.

**Comment by damienbod** [comment]
ASP.NET Core 2.0 now

**Comment by robisim74** [comment]
In 5 minutes...!
