### ISSUE TITLE
Adding frontend testing

### ISSUE THREAD

**Issue by damienbod** [damienbod/AngularWebpackVisualStudio#31]

**Comment by robisim74** [comment]
@damienbod @FabianGosebrink 

I added Angular testing:
- I created _angularApp/tests_ folder for _.spec.ts_ files: but all the _specs_ files in _angularApp_ will be used if they will be put next to the things they test
- I added _karma.conf.js_ for Karma test runner
- I created _config_ folder in the root of the project, and I added there _webpack.test.js_ file used by Karma to build the test and _spec.bundle.js_ that contains its context: I think we should move other configuration files in this folder, because they are growing...
- I updated the README with an essential explanation of the tests (feel free to extend it!)

Greetings,
Roberto

**Comment by damienbod** [comment]
excellent, thanks a million

**Comment by FabianGosebrink** [comment]
Looks great, thanks a lot @robisim74 !!!
