### ISSUE TITLE
Getting Error when Adding Template Form

### ISSUE THREAD

**Issue by nssidhu** [damienbod/AngularWebpackVisualStudio#65]
I am getting the following Error(7 of them), when adding new Template Form.

EXCEPTION: Uncaught (in promise): TypeError: Cannot set property stack of [object Object] which has only a getter
TypeError: Cannot set property stack of [object Object] which has only a getter
    at assignAll (http://localhost:8080/dist/app.bundle.js:112590:29)

```
<form novalidate class="form-inline" (ngSubmit)="searchEmployer()" >
            <div class="form-group" >
                <label class="sr-only" >Employer Name</label>
                    <input type="text" class="form-control" placeholder="Employer Name ..." [(ngModel)]="employer.name" >
            </div>
            <button type="submit" class="btn btn-primary" >Search Employer</button>
        </form>
```

If i remove the Input Tag with ngModel i don't get any Error.

What am i doing Wrong?

**Comment by FabianGosebrink** [comment]
Hey @nssidhu , 
first of all you have to use the "name"-attribute when using "ngModel" because angular needs to know under which name it should take care of the model you gave it in the directive `ngModel`.

The error message depends a bit on what you are doing in your underlying component in typescript...

BR

**Comment by damienbod** [comment]
Can I close this?
